server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/edurating?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 20010503


mybatis:
  mapper-locations: classpath:mapper/*.xml